### ISSUE TITLE
Integrate Boostrap

### ISSUE THREAD

**Issue by dfsantos-source** [wgwyneth/cs320-AST-frontend#1]
Integrate bootstrap into the frontend so we can have components to use right out of the box as opposed to developing CSS from scratch. 

It should be as simple as adding a link to index.html:

`<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">`

More information here:https://getbootstrap.com/docs/4.3/getting-started/introduction/

**Comment by chetangoel01** [comment]
https://github.com/wgwyneth/cs320-AST-frontend/pull/7
